// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{
  /////////////////////////////////////////////////////////////////////////////
  // light vector
  float theta = 0.25 * M_PI * animation_seconds; 
  vec4 light4 = view * vec4(3*cos(theta), 3, 3*sin(theta), 1);
  vec3 light3 = normalize(light4 - view_pos_fs_in).xyz;
  // view vector
  vec3 v = - normalize(view_pos_fs_in.xyz);
  // normal vector 
  vec3 n = normalize(normal_fs_in);

  float phong = 800.0;
  vec3 ka = vec3(0.05, 0.05, 0.05);

  // turbulence
  float k1 = 13;
  float k2 = 5;
  float w = 2;
  float noise = ( 1 + sin( k1 * ( sphere_fs_in.z + perlin_noise(k2*sphere_fs_in) ) )/w )/2; // taken from textbook

  if (is_moon) {
    vec3 kd = vec3(0.5,  0.5,  noise);
    vec3 ks = vec3(0.9,  0.9,  0.9);
    color = blinn_phong(ka, kd, ks, phong, n, v, light3);
  }
  else {
    vec3 kd = vec3(0.2,  0.2,  noise);
    vec3 ks = vec3(0.9,  0.9,  0.9);
    color = blinn_phong(ka, kd, ks, phong, n, v, light3);
  }
  /////////////////////////////////////////////////////////////////////////////
}
